@startuml
skinparam backgroundColor White
skinparam ActivityBackgroundColor White
skinparam ActivityBorderColor Black
skinparam ActivityDiamondBackgroundColor White
skinparam ActivityDiamondBorderColor Black
skinparam ArrowColor Black
skinparam PartitionBorderColor Black
skinparam PartitionBackgroundColor White
skinparam defaultFontSize 14

title Activity Diagram Manajemen Tagihan

|Admin|
start
:Tap Menu Tagihan;

|Sistem|
:Memuat Data Tagihan;
:Hitung Summary;
:Menampilkan Daftar Tagihan;

|Admin|
if (Aksi?) then (Filter)
  :Pilih Filter;
  |Sistem|
  :Filter Tagihan;
else if (Aksi?) then (Tap Card)
  |Sistem|
  :Buka Modal Detail;
  |Admin|
  if (Sub Aksi?) then (Edit)
    :Edit Data;
    |Sistem|
    :Simpan;
  else (Delete)
    |Sistem|
    :Hapus Tagihan;
  endif
else (Tap FAB)
  |Sistem|
  :Buka Modal Tambah;
  |Admin|
  :Cari Mahasiswa;
  :Input Tipe, Nominal;
  |Sistem|
  :Simpan Tagihan Baru;
endif

stop

@enduml

