@startuml
skinparam backgroundColor White
skinparam ActivityBackgroundColor White
skinparam ActivityBorderColor Black
skinparam ActivityDiamondBackgroundColor White
skinparam ActivityDiamondBorderColor Black
skinparam ArrowColor Black
skinparam PartitionBorderColor Black
skinparam PartitionBackgroundColor White
skinparam defaultFontSize 14

title Activity Diagram Pencarian Mahasiswa

|Mahasiswa|
start
:Tap Menu Pencarian;

|Sistem|
:Menampilkan\nHalaman Pencarian;

|Mahasiswa|
:Mengetik Kata Kunci;

|Sistem|
:Mencari Data Terkait;

if (Hasil Ditemukan?) then (Ya)
  :Menampilkan\nHasil Pencarian;
  |Mahasiswa|
  if (Tap Hasil?) then (Ya)
    |Sistem|
    :Menampilkan\nDetail Item;
  endif
else (Tidak)
  :Menampilkan\nPesan Kosong;
endif

stop

@enduml

